function varargout=sym_mvdP(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:7);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',4);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('sym_mvdP_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});




function [out1,out2,out3] = sym_mvdP_rhs_0(x1,x2,x3,p1,p2,p3,p4,x1_dev,x2_dev,x3_dev,p1_dev,p2_dev,p3_dev,p4_dev)
%SYM_MVDP_RHS_0
%    [OUT1,OUT2,OUT3] = SYM_MVDP_RHS_0(X1,X2,X3,P1,P2,P3,P4,X1_DEV,X2_DEV,X3_DEV,P1_DEV,P2_DEV,P3_DEV,P4_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Mar-2021 18:53:35

t2 = 1.0./p2;
t3 = -x3;
t4 = t3+x1;
t5 = t2.*t4;
out1 = -(t5+x2-p4.*(x1-x1.^3./3.0))./p1;
if nargout > 1
    out2 = -p3+x1;
end
if nargout > 2
    out3 = t5;
end


function [out1,out2,out3] = sym_mvdP_rhs_1(x1,x2,x3,p1,p2,p3,p4,x1_dev,x2_dev,x3_dev,p1_dev,p2_dev,p3_dev,p4_dev)
%SYM_MVDP_RHS_1
%    [OUT1,OUT2,OUT3] = SYM_MVDP_RHS_1(X1,X2,X3,P1,P2,P3,P4,X1_DEV,X2_DEV,X3_DEV,P1_DEV,P2_DEV,P3_DEV,P4_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Mar-2021 18:53:36

t2 = x1.^3;
t3 = 1.0./p2;
t5 = -x3;
t6 = -x3_dev;
t4 = t3.^2;
t7 = t5+x1;
t8 = t6+x1_dev;
t9 = t2./3.0;
t10 = -t9;
t12 = t3.*t8;
t13 = p2_dev.*t4.*t7;
out1 = -(t12-t13+x2_dev-p4.*(x1_dev-x1.^2.*x1_dev)+p4_dev.*(t9-x1))./p1+1.0./p1.^2.*p1_dev.*(x2+t3.*t7+p4.*(t9-x1));
if nargout > 1
    out2 = -p3_dev+x1_dev;
end
if nargout > 2
    out3 = t12-t13;
end


function [out1,out2,out3] = sym_mvdP_rhs_2(x1,x2,x3,p1,p2,p3,p4,x1_dev,x2_dev,x3_dev,p1_dev,p2_dev,p3_dev,p4_dev)
%SYM_MVDP_RHS_2
%    [OUT1,OUT2,OUT3] = SYM_MVDP_RHS_2(X1,X2,X3,P1,P2,P3,P4,X1_DEV,X2_DEV,X3_DEV,P1_DEV,P2_DEV,P3_DEV,P4_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Mar-2021 18:53:36

t2 = p2_dev.^2;
t3 = x1.^2;
t4 = x1.^3;
t5 = 1.0./p2;
t8 = -x3;
t9 = -x3_dev;
t6 = t5.^2;
t7 = t5.^3;
t10 = t3.*x1_dev;
t11 = t8+x1;
t12 = t9+x1_dev;
t13 = t4./3.0;
t14 = -t10;
t15 = -t13;
t18 = p2_dev.*t6.*t12.*2.0;
t19 = t2.*t7.*t11.*2.0;
out1 = -(-t18+t19+p4_dev.*(t10-x1_dev).*2.0+p4.*x1.*x1_dev.^2.*2.0)./p1+1.0./p1.^2.*p1_dev.*(x2_dev+t5.*t12+p4.*(t10-x1_dev)+p4_dev.*(t13-x1)-p2_dev.*t6.*t11).*2.0-1.0./p1.^3.*p1_dev.^2.*(x2+t5.*t11+p4.*(t13-x1)).*2.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = -t18+t19;
end

